############################################################
# StaBiCut v2 — Multi-gene panel helpers
# File: R/Panel_helper_StaBiCut_v2.R
#
# Scope:
#   Helper functions for assembling multi-gene visualization sheets from
#   cached outputs generated by run_batch_sur_cutpoint_analysis_v2().
#   These functions do not re-run survival analysis or bootstrap scanning;
#   they only re-use previously computed statistics and plotting inputs.
#
# Included in this file:
#   - small internal layout helpers
#   - a pure row-builder for one gene
#   - a sheet-level exporter for multiple genes
#
# Expected upstream objects:
#   - results_df
#   - df_cache
#   - boot_cache
#   - scan_cache
#   - optional expected_dir_table
#
# Dependencies assumed to be available after sourcing:
#   - modules_core_StaBiCut_v2.R
#   - modules_plot_single_StaBiCut_v2.R
#
# Notes:
#   - This script does not load data, call rm(list = ls()), or attach packages.
#   - Plot saving occurs only in the sheet-level wrapper.
############################################################

# ==========================================================
# Internal layout helpers
# ==========================================================

#' Apply consistent outer margins to a ggplot panel
#'
#' @param p A ggplot object.
#' @param t,r,b,l Numeric scalars giving top, right, bottom, and left margins
#'   in points.
#'
#' @return A ggplot object with updated plot margins.
.set_panel_margin_v2 <- function(p, t = 6, r = 6, b = 6, l = 6) {
  p + ggplot2::theme(plot.margin = ggplot2::margin(t, r, b, l))
}

#' Apply a fixed aspect ratio to a ggplot panel
#'
#' @param p A ggplot object.
#' @param ratio Numeric scalar giving the panel aspect ratio (height / width).
#'
#' @return A ggplot object with a fixed aspect ratio.
.force_square_panel_v2 <- function(p, ratio = 1) {
  p + ggplot2::theme(aspect.ratio = ratio)
}

#' Create an output directory if it does not already exist
#'
#' @param path Character scalar giving a directory path.
#'
#' @return Invisibly returns `TRUE`.
.ensure_dir_v2 <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE, showWarnings = FALSE)
  invisible(TRUE)
}

#' Build a left-side row-tag panel for multi-gene sheets
#'
#' @param label Character scalar, typically a single row tag such as `"A"` or
#'   `"B"`.
#'
#' @return A ggplot object containing only the supplied label.
.make_row_label_plot_v2 <- function(label) {
  ggplot2::ggplot() +
    ggplot2::annotate("text", x = 0, y = 0, label = label,
                      fontface = "bold", size = 6, hjust = 0, vjust = 1) +
    ggplot2::coord_cartesian(xlim = c(0, 1), ylim = c(-1, 0)) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.margin = ggplot2::margin(6, 2, 6, 6)
    )
}

# ==========================================================
# 1. Single-row builder
# ==========================================================

#' Build one four-panel gene row for a multi-gene StaBiCut sheet
#'
#' This function is intentionally pure: it constructs and returns a patchwork row
#' for a single gene, but does not write any files to disk. It is designed for
#' downstream composition into multi-gene sheets after the analytical results have
#' already been computed by `run_batch_sur_cutpoint_analysis_v2()`.
#'
#' The returned row contains four evidence panels:
#' \enumerate{
#'   \item cutoff scan (Wald statistic across candidate cutoffs),
#'   \item tumor-expression density with the selected cutoff,
#'   \item bootstrap cutoff-density plot,
#'   \item Kaplan-Meier plot at the selected cutoff.
#' }
#'
#' @param df Data frame for one gene, typically taken from `df_cache[[gene]]`.
#'   Must contain `expr`, `time`, `event`, and the cutoff-defined grouping used
#'   for Kaplan-Meier plotting.
#' @param gene Character scalar giving the gene symbol.
#' @param best_cut Numeric scalar giving the selected cutoff.
#' @param hr Numeric scalar giving the hazard ratio at `best_cut`.
#' @param ci_low Numeric scalar giving the lower 95% confidence bound for `hr`.
#' @param ci_high Numeric scalar giving the upper 95% confidence bound for `hr`.
#' @param p_cutoff Numeric scalar giving the log-rank P value displayed in the
#'   Kaplan-Meier panel.
#' @param boot Named list for one gene, typically taken from `boot_cache[[gene]]`.
#'   Must contain bootstrap summaries compatible with
#'   `build_bootstrap_density_plot_clean_v2()`, including `boot_cuts`, `iqr`,
#'   `ci_low`, and `ci_high`.
#' @param scan_df Data frame of admissible candidate cutoffs and scan statistics,
#'   typically taken from `scan_cache[[gene]]`.
#' @param expected_dir Character scalar or `NULL` giving the expected hazard
#'   direction carried over from the StaBiCut analysis. When provided, candidate
#'   cutoffs in the scan panel are visually flagged according to whether their
#'   estimated hazard ratio is direction-compatible with this expected direction.
#' @param widths Numeric vector of length 4 giving column widths for the four
#'   panels. The first three panels are typically kept equal, whereas the
#'   Kaplan-Meier panel is slightly narrower in the current layout.
#' @param km_aspect Numeric scalar giving the aspect ratio of the Kaplan-Meier
#'   panel.
#' @param xps_aspect Numeric scalar giving the aspect ratio of the first three
#'   panels.
#' @param row_tag Optional character scalar used to label the entire row (for
#'   example `"A"`, `"B"`, `"C"`). If `NULL`, no left-side row tag is drawn.
#' @param tag_width Numeric scalar giving the relative width allocated to the
#'   optional row-tag column.
#' @param km_show_legend Logical; if `TRUE`, the Kaplan-Meier legend is shown at
#'   the top of the KM panel.
#'
#' @return A patchwork object representing one assembled gene row.
#' @export
make_gene_row_main_v2 <- function(
    df,
    gene,
    best_cut,
    hr, ci_low, ci_high, p_cutoff,
    boot,
    scan_df,
    expected_dir = NULL,
    widths = c(1.15, 1.15, 1.15, 0.72),
    km_aspect = 1,
    xps_aspect = 0.625,
    row_tag = NULL,
    tag_width = 0.18,
    km_show_legend = TRUE
) {
  # A: cut scan
  if (!is.null(scan_df) && is.data.frame(scan_df) && nrow(scan_df) > 0) {
    scan_df$pass_dir <- TRUE
    if (!is.null(expected_dir)) {
      if (expected_dir == "protective_high") scan_df$pass_dir <- scan_df$hr < 1
      if (expected_dir == "adverse_high")    scan_df$pass_dir <- scan_df$hr > 1
    }
    
    pA <- ggplot2::ggplot(scan_df, ggplot2::aes(x = cut, y = wald)) +
      ggplot2::geom_line(linewidth = 0.7) +
      ggplot2::geom_point(ggplot2::aes(alpha = pass_dir), size = 1.5) +
      ggplot2::geom_vline(xintercept = best_cut, linetype = "dashed", color = "#ea4846",linewidth = 1) +
      ggplot2::theme_minimal(base_size = 12) +
      ggplot2::labs(
        title = paste0("Cut scan: ", gene),
        subtitle = paste0(
          "best_cut = ", signif(best_cut, 4),
          if (!is.null(expected_dir)) paste0(" | ", expected_dir) else ""
        ),
        x = "Cutoff",
        y = "Wald statistic"
      ) +
      ggplot2::scale_alpha_manual(values = c(`TRUE` = 1, `FALSE` = 0.15), guide = "none") +
      ggplot2::theme(aspect.ratio = xps_aspect)
  } else {
    pA <- ggplot2::ggplot() +
      ggplot2::theme_void() +
      ggplot2::labs(title = paste0("Cut scan: ", gene), subtitle = "scan_df unavailable")
  }
  
  # B: expression density
  pB <- build_expr_density_plot_v2(df$expr, gene, best_cut) +
    ggplot2::theme(aspect.ratio = xps_aspect, legend.position = "none")
  
  # C: bootstrap density
  expr_iqr <- stats::IQR(df$expr, na.rm = TRUE)
  
  if (!is.finite(expr_iqr) || expr_iqr <= 0 ||
      !is.finite(boot$iqr) || !is.finite(boot$ci_low) || !is.finite(boot$ci_high)) {
    IQR_rel <- NA_real_
    CI_rel <- NA_real_
    boot_score_rel <- NA_real_
  } else {
    k1 <- 3
    k2 <- 2
    IQR_rel <- boot$iqr / expr_iqr
    CI_rel  <- (boot$ci_high - boot$ci_low) / expr_iqr
    boot_score_rel <- exp(-k1 * IQR_rel) * exp(-k2 * CI_rel)
  }
  
  pC <- build_bootstrap_density_plot_clean_v2(bootstrap_cutoffs = boot$boot_cuts,cutoff = best_cut,
                                              gene = gene,IQR_rel = IQR_rel,CI_rel = CI_rel,
                                              bootstrap_score = boot_score_rel) +
    ggplot2::theme(aspect.ratio = xps_aspect,legend.position = "none")
  
  # D: KM
  pD <- build_survival_plot_v2(
    df = df,
    gene = gene,
    hr = hr,
    ci_low = ci_low,
    ci_high = ci_high,
    pval = p_cutoff
  ) +
    ggplot2::theme(
      aspect.ratio = km_aspect,
      legend.position = if (isTRUE(km_show_legend)) "top" else "none"
    ) +
    ggplot2::coord_cartesian(ylim = c(0, 1), clip = "off")
  
  # unify margins
  pA <- .set_panel_margin_v2(pA, 2, 2, 2, 2)
  pB <- .set_panel_margin_v2(pB, 2, 2, 2, 2)
  pC <- .set_panel_margin_v2(pC, 2, 2, 2, 2)
  pD <- .set_panel_margin_v2(pD, 2, 2, 4, 2)
  pD <- .set_panel_border_v2(pD)
  
  # compose one row
  if (!is.null(row_tag) && is.character(row_tag) && nchar(row_tag) == 1) {
    pTag <- .make_row_label_plot_v2(row_tag)
    row_panel <- (pTag | pA | pB | pC | pD) +
      patchwork::plot_layout(widths = c(tag_width, widths), guides = "keep")
  } else {
    row_panel <- (pA | pB | pC | pD) +
      patchwork::plot_layout(widths = widths, guides = "keep")
  }
  
  return(row_panel)
}

# ==========================================================
# 2. Multi-gene sheet exporter
# ==========================================================

#' Assemble and save a multi-gene StaBiCut sheet from cached results
#'
#' This function rebuilds a multi-gene PDF sheet by iterating over a requested
#' gene order and reusing cached plotting inputs produced during the main
#' StaBiCut run. It does not repeat cutoff scanning or bootstrap analysis.
#'
#' For each gene retained in `gene_order`, the function retrieves:
#' \itemize{
#'   \item the per-gene statistics from `results_df`,
#'   \item the analysis table from `df_cache`,
#'   \item the bootstrap summaries from `boot_cache`,
#'   \item the cutoff-scan table from `scan_cache`,
#'   \item and, optionally, the expected direction from `expected_dir_table`.
#' }
#'
#' Each row is built with `make_gene_row_main_v2()` and then stacked into a
#' single-column patchwork layout.
#'
#' @param gene_order Character vector giving the genes to display, in the final
#'   row order desired in the output sheet.
#' @param results_df Data frame returned by the StaBiCut pipeline. Must contain
#'   at least `Gene`, `Cutoff`, `HR`, `CI_low`, `CI_high`, and `Cutoff_P`.
#' @param df_cache Named list of per-gene analysis tables, usually returned by
#'   `run_batch_sur_cutpoint_analysis_v2()`.
#' @param boot_cache Named list of per-gene bootstrap results, usually returned
#'   by `run_batch_sur_cutpoint_analysis_v2()`.
#' @param scan_cache Named list of per-gene cutoff-scan tables, usually returned
#'   by `run_batch_sur_cutpoint_analysis_v2()`.
#' @param expected_dir_table Optional data frame containing `Gene` and
#'   `expected_dir`. For each plotted gene, the matched expected hazard
#'   direction is passed to the row builder and used to visually indicate
#'   direction compatibility in the cutoff-scan panel.
#' @param out_pdf Character scalar giving the output PDF path.
#' @param width,height Numeric scalars passed to `ggplot2::ggsave()`.
#' @param widths Numeric vector of length 4 giving relative widths for the four
#'   panel columns.
#' @param km_aspect Numeric scalar giving the aspect ratio of the Kaplan-Meier
#'   panels.
#' @param xps_aspect Numeric scalar giving the aspect ratio of the first three
#'   panels.
#' @param show_row_tags Logical; if `TRUE`, adds row-level tags (`A`, `B`, `C`,
#'   ...) on the left side of the sheet.
#'
#' @return Invisibly returns the assembled patchwork sheet.
#' @export
plot_multi_gene_sheet_main_v2 <- function(
    gene_order,
    results_df,
    df_cache,
    boot_cache,
    scan_cache,
    expected_dir_table = NULL,
    out_pdf,
    width = 25.5,
    height = 24,
    widths = c(1.15, 1.15, 1.15, 0.72),
    km_aspect = 1,
    xps_aspect = 0.625,
    show_row_tags = TRUE
) {
  stopifnot(is.character(gene_order) && length(gene_order) >= 1)
  stopifnot(is.data.frame(results_df))
  stopifnot(is.list(df_cache) && is.list(boot_cache) && is.list(scan_cache))
  stopifnot(is.character(out_pdf) && length(out_pdf) == 1)
  
  required_cols <- c("Gene", "Cutoff", "HR", "CI_low", "CI_high", "Cutoff_P")
  missing_cols <- setdiff(required_cols, colnames(results_df))
  if (length(missing_cols) > 0) {
    stop("plot_multi_gene_sheet_main_v2(): results_df is missing columns: ",
         paste(missing_cols, collapse = ", "))
  }
  
  gene_ok <- gene_order[
    gene_order %in% names(df_cache) &
      gene_order %in% names(boot_cache) &
      gene_order %in% names(scan_cache)]
  
  if (length(gene_ok) == 0) {
    stop("None of requested genes are available in caches /df.")
  }
  
  rows <- lapply(seq_along(gene_ok), function(i) {
    g <- gene_ok[[i]]
    row_stat <- results_df[match(g, results_df$Gene), , drop = FALSE]
    if (nrow(row_stat) == 0) {
      stop("Gene not found in results_df: ", g)
    }
    
    df_g   <- df_cache[[g]]
    boot_g <- boot_cache[[g]]
    scan_g <- scan_cache[[g]]
    
    expected_dir_g <- NULL
    if (!is.null(expected_dir_table) && is.data.frame(expected_dir_table) &&
        all(c("Gene", "expected_dir") %in% colnames(expected_dir_table))) {
      tmp <- expected_dir_table$expected_dir[match(g, expected_dir_table$Gene)]
      if (length(tmp) == 1 && !is.na(tmp)) expected_dir_g <- tmp
    }
    
    make_gene_row_main_v2(
      df = df_g,
      gene = g,
      best_cut = as.numeric(row_stat$Cutoff),
      hr = as.numeric(row_stat$HR),
      ci_low = as.numeric(row_stat$CI_low),
      ci_high = as.numeric(row_stat$CI_high),
      p_cutoff = as.numeric(row_stat$Cutoff_P),
      boot = boot_g,
      scan_df = scan_g,
      expected_dir = expected_dir_g,
      widths = widths,
      km_aspect = km_aspect,
      xps_aspect = xps_aspect,
      row_tag = if (isTRUE(show_row_tags)) LETTERS[i] else NULL,
      km_show_legend = TRUE
    )
  })
  
  sheet <- patchwork::wrap_plots(rows, ncol = 1) +
    patchwork::plot_layout(guides = "keep")
  
  .ensure_dir_v2(dirname(out_pdf))
  ggplot2::ggsave(out_pdf, plot = sheet, width = width, height = height, limitsize = FALSE)
  
  invisible(sheet)
}
